2015-04-15 14:41:18,446 - softwarecenter.ui.gtk3.app - INFO - setting up proxy 'None'
2015-04-15 14:41:37,711 - softwarecenter.region - WARNING - failed to use geoclue: 'org.freedesktop.Geoclue.Error.notAvailable: Geoclue master client has no usable Address providers'
2015-04-15 14:41:40,660 - softwarecenter.backend.reviews - WARNING - Could not get usefulness from server, no username in config file
2015-04-15 14:41:40,730 - softwarecenter.plugin - INFO - activating plugin '<module 'webapps_activation' from '/usr/share/software-center/softwarecenter/plugins/webapps_activation.pyc'>'
2015-04-15 14:41:42,067 - softwarecenter.db.pkginfo_impl.aptcache - INFO - aptcache.open()
2015-04-15 14:42:26,908 - softwarecenter.backend.spawn_helper - WARNING - exit code 1 from helper for '['/usr/share/software-center/piston_generic_helper.py', '--datadir', '/usr/share/software-center/', 'SoftwareCenterAgentAPI', 'available_apps', '{"lang": "zh_CN", "series": "trusty", "arch": "i386"}']'
2015-04-15 14:42:26,925 - softwarecenter.backend.spawn_helper - WARNING - got error from helper: 'WARNING:__main__:no data
'
2015-04-15 14:42:26,937 - softwarecenter.db.update - WARNING - update_from_software_center_agent: error: 'WARNING:__main__:no data\n'
2015-04-15 14:42:28,673 - softwarecenter.db.utils - INFO - software-center-agent finished with status 1
2015-04-15 14:42:29,411 - softwarecenter.backend.spawn_helper - WARNING - exit code 1 from helper for '['/usr/share/software-center/piston_generic_helper.py', '--datadir', '/usr/share/software-center/', 'RatingsAndReviewsAPI', 'review_stats']'
2015-04-15 14:42:29,415 - softwarecenter.backend.spawn_helper - WARNING - got error from helper: 'WARNING:__main__:no data
'
2015-04-15 14:42:32,780 - softwarecenter.backend.spawn_helper - WARNING - exit code 1 from helper for '['/usr/share/software-center/piston_generic_helper.py', '--datadir', '/usr/share/software-center/', 'SoftwareCenterAgentAPI', 'exhibits', '{"lang": "zh_CN", "series": "trusty"}']'
2015-04-15 14:42:32,783 - softwarecenter.backend.spawn_helper - WARNING - got error from helper: 'WARNING:__main__:no data
'
